services:
  - mysql

environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      platform: x64
      STANDALONE: "FALSE"
      CONDA_PY: "36"
      CONDA_BUILD: "TRUE"
      SPLIT_RUN: "FALSE"
#  PMG_MAPI_KEY:
#    secure: XIbk1W27nucVUHTVpIL2B+FodL9w2Efyw5PqTdnfbHg=
  PYPIPWD:
    secure: QPpXonUAeLJ8p3f936jh7g==
install:
  # Add the paths
  - 'set PATH=%PYTHON%;%PYTHON%\Library\bin;%PYTHON%\Scripts;%PATH%'
  - 'set MPLBACKEND=Agg'
  - 'conda config --system --add channels conda-forge'
  # Install the build dependencies of the project via conda and pip
  - 'conda install --yes --quiet numpy scipy matplotlib sympy cython pandas pip python-igraph'
  # - 'conda update --yes --all'
  - 'pip install --upgrade numpy'
  - 'pip install -r requirements.txt'
  - 'pip install pybtex pytest pytest-cov ase coveralls fdint ase twine networkx'
  # Note that pyhull is excluded because it does not work on Windows.
  # Run develop to install in dev mode and build C extension.
  - "python setup.py develop"

build: false

test_script:
  - "pytest --ignore=pymatgen/ext/tests/test_matproj.py --ignore=pymatgen/analysis/tests/test_pourbaix_diagram.py --ignore=pymatgen/tests/test_init.py --ignore-glob='pymatgen/analysis/defects/tests/test_*.py' pymatgen"

notifications:
  - provider: Email
    to:
      - shyuep@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy_script:
   - IF "%APPVEYOR_REPO_BRANCH%" == "stable" (python setup.py sdist bdist_wheel)
   - IF "%APPVEYOR_REPO_BRANCH%" == "stable" (twine upload --username Shyue.Ping.Ong --password %PYPIPWD% dist/*.whl)
